### ISSUE TITLE
Question for 322bus

### ISSUE THREAD

**Issue by TangDavidResearch** [xuwkk/gen_pandapower_pv#3]
When I run bus322, I get the following error, I hope the author can help me.

D:\software\python\python.exe "C:/Users/David town/Desktop/generation_network/bus322.py"
pandas version: 1.5.3
pandapower version: 2.13.1
the total load of MV is 3.068

The low-voltage nets:
Traceback (most recent call last):
  File "C:/Users/David town/Desktop/generation_network/bus322.py", line 88, in <module>
    LV_net = pp.from_pickle(f'LV_network/LV{i}.p')
  File "D:\software\python\lib\site-packages\pandapower\file_io.py", line 183, in from_pickle
    io_utils.transform_net_with_df_and_geo(net, ["bus_geodata"], ["line_geodata"])
  File "D:\software\python\lib\site-packages\pandapower\io_utils.py", line 322, in transform_net_with_df_and_geo
    df_index = pd.Index(df_dict['index'], dtype=numpy.int64)
  File "D:\software\python\lib\site-packages\pandas\core\indexes\base.py", line 572, in __new__
    return Index(subarr, dtype=dtype, copy=copy, name=name, **kwargs)
  File "D:\software\python\lib\site-packages\pandas\core\indexes\base.py", line 516, in __new__
    data = sanitize_array(data, None, dtype=dtype, copy=copy)
  File "D:\software\python\lib\site-packages\pandas\core\construction.py", line 597, in sanitize_array
    subarr = _try_cast(data, dtype, copy, raise_cast_failure)
  File "D:\software\python\lib\site-packages\pandas\core\construction.py", line 835, in _try_cast
    subarr = maybe_cast_to_integer_array(arr, dtype)
  File "D:\software\python\lib\site-packages\pandas\core\dtypes\cast.py", line 1836, in maybe_cast_to_integer_array
    casted = arr.astype(dtype, copy=copy)
ValueError: invalid literal for int() with base 10: 'hL'

**Comment by TangDavidResearch** [comment]
detail :
   
    LV_net = pp.from_pickle(f'LV_network/LV{i}.p')
